// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhZ4Fap2KS8bfKQkW7OVArxASE436Rlc',
    appId: '1:291486476558:android:9b4274f3940e4deb0b4f5f',
    messagingSenderId: '291486476558',
    projectId: 'mynotes-x',
    storageBucket: 'mynotes-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrD-lzwLoGYZAwcgF38oS9mWqADJWVdc',
    appId: '1:291486476558:ios:3889954c15d095920b4f5f',
    messagingSenderId: '291486476558',
    projectId: 'mynotes-x',
    storageBucket: 'mynotes-x.appspot.com',
    androidClientId: '291486476558-b73b98pp45f9d1d0kjmgin674mr49out.apps.googleusercontent.com',
    iosClientId: '291486476558-76d4eriv0fevk5qnsooeqldi97emffmp.apps.googleusercontent.com',
    iosBundleId: 'me.soumyo.mynotes',
  );

}